### ISSUE TITLE
Continuous Integration fails to download miktex portable

### ISSUE THREAD

**Issue by yoonsikp** [mnemosyne-proj/mnemosyne#119]
wget fails on the url http://mirrors.ctan.org/systems/win32/miktex/setup/windows-x86/miktex-portable.exe

Instead use http://mirrors.ctan.org/systems/win32/miktex/setup/windows-x86/portable-miktex.exe

**Comment by pbienst** [comment]
Julian, since you set this up, could have a look at this? Thanks!

**Comment by three-comrades** [comment]
Will do.

**Comment by jmehne** [comment]
Turns out, miktex portable is [discontinued](https://miktex.org/announcement/miktex-portable-sfx-discontinued) in the flavor we were using here. It used to be possible to simply extract the file with 7zip. That doesn't work any more (`Can not open the file as archive`) with the currently available installers and unfortunately I couldn't figure out an easy way to do an unattended install with the new file.

I will disable it for now, because the failing builds are misleading.
