### ISSUE TITLE
line endings in github repository

### ISSUE THREAD

**Issue by pbienst** [mnemosyne-proj/mnemosyne#33]
See https://groups.google.com/d/msgid/mnemosyne-proj-users/448dbd34-0e91-459f-8285-d0861f48386b%40googlegroups.com?utm_medium=email&utm_source=footer

I tried to make sure my editor used LF instead of CRLF, and set 'git config --global core.autocrlf true'.

However, when I do a git diff, it says it will replace LF by CRLF when committing.

**Comment by three-comrades** [comment]
Argh. Sorry I didn't catch this, I hope it doesn't cause any more fallout.

Just to be sure: I assume you develop on Windows?

Alright, I think this is what happened: currently, mnemosyne repository contains files that have LF line endings and files that have CRLF line endings. Internally, git stores these files correctly. The `pyqt_ui/mnemosyne` file in question is stored with LF line endings (which is correct). But, on Windows, `core.autocrlf true` means that git translates all LF line endings to CRLF endings. So, on your file system, the `pyqt_ui/mnemosyne` file has CRLF line endings, although internally git stores it as LF. And because you probably built the release tarball from your Windows computer, the wrong file endings ended up in the tar ball.

> However, when I do a git diff, it says it will replace LF by CRLF when committing.

Does this happen when you edit `pyqt_ui/mnemosyne` or a different file? Because I don't quite get why that would happen to `pyqt_ui/mnemosyne` that seems internally to be stored with LF line endings.

Hm ... so how should we handle this? To be honest, I don't quite get how this used to work. Did bzr on windows not translate the line endings, so you'd actually have files with LF and CRLF endings in the same directory? If so, what happened then if you edited the `pyqt_ui/mnemosyne` file with an editor that was set to `CRLF` - did bzr commit that as-is, so you would end up with a file with mixed line endings?

**Comment by pbienst** [comment]
Yes, I develop under Windows, and your explanation of what happened seems plausible.

Just for fun, I tried with `core.autocrlf false`, and now it does not complain anymore, but also does not detect a diff if I change the line endings.

So I guess the issue is solved this way.

Not sure if it's a regression with respect to bzr, it could be that it's specific to the shell the bug reporter was using.

**Comment by three-comrades** [comment]
Hm, `core.autocrlf false` should work, if your editor is smart enough to automatically determine the right line ending. Notepad++ seems to do so. The downside seems to be, that git happily accepts CRLF in a LF file and vice versa, so that theoreticall we could end up with mixed line endings.

What we could do:
- not care. If you`core.autocrlf false` works for you and you never use a more naive editor like notepad, this should never happen.
- convert all line endings to LF
- add a pre-commit hook that is run before `commit` that checks each file to be committed for mixed CRLF and LF line endings and throws an error, if it finds mixed line endings.
- use `core.autocrlf true` and add exceptions in the `.gitattributes` file for every file starting with a shebang `#!` - about twenty files in the repository.

Btw, for the record and future reference, because it took me forever to find out. If you change the value of `core.autocrlf` and want git to recreate the files with the correct endings, run the following commands from a clean working directory (any changes that weren't committed will be lost):
```
git checkout master
git config core.autocrlf false
git read-tree --empty
git reset --hard master
```
LF and CRLF line endings can be shown on the command line with `cat -ve <file>`. vim needs to be started with the `-b` switch and `:set list`. In vim, CR can be inserted with ctrl-v+ctrl-m.
