### ISSUE TITLE
Browse Cards and Add/Edit Card stealing focus

### ISSUE THREAD

**Issue by dbedrenko** [mnemosyne-proj/mnemosyne#81]
Often when I'm adding/editing a card, I want to check existing cards, for example, to double check that I'm not writing a duplicate or to reference something that is mentioned in another card. This is not possible: the app doesn't let me open Browse Cards. At this time neither is it possible to go through flash cards (the main view with "Show answer"). 

Likewise you cannot go through flash cards at the same time as having Browse Cards open, it completely steals the focus.

It would make managing, editing and cross-referencing cards a lot easier if the focus wouldn't be stolen. Currently, I have to:

1. Save the card I was adding mid-way
2. Open Browse Cards to check another card
3. Memorise this other card and close it
4. Edit the original card I did not finish
5. Naturally I failed to fully remember the other card, so go back to step 1.

This is quite cumbersome.

PS: I love this application! It's so useful for studying and note-taking. Thank you for all your effort!

**Comment by pbienst** [comment]
This is less trivial than it sounds, because you would then be able to edit cards from both windows, and there's a potential for database corruption.

Anyway, for feature requests, please use the uservoice forum, which allows people to vote for features. I seem to recall what you suggest to be already there, so you can add your vote to it.
